groups:
  - name: prometheus-rules-example
    rules:
      - alert: down
        expr: up == 0
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: prometheus-rules-example
