apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/mg500/helm-charts'
  destinations:
    - namespace: 'argocd'
      server: '*'
  clusterResourceBlacklist:
    - group: '*'
      kind: '*'