apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    #chart: sealed-secrets
    repoURL: https://github.com/mg500/helm-charts
    targetRevision: main
    path: charts/argocd/deployments
    #helm:
    #  releaseName: sealed-secrets
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true