grafanaProvisioning:
  enabled: true
  dashboards:
    enabled: true
    label: grafana_dashboard
    labelValue: "1"
    directory: dashboards
    ## Set the folder in which the dashboards will be stored ("General" is not possible)
    grafanaDefaultFolder: Custom
    ## Transfer the folder structure from your directory to grafana
    ## grafanaDefaultFolder does not matter in this case
    transferFolderStructure: true

alertmanagerProvisioning:
  enabled: true
  directory: alerts


alertmanagerConfig:
  enabled: true
  name: alertmanager-config

  mailGroups:
    - name: test-1
      to: "test-1@gmx.de"
      matchers:
        - matchType: "="
          name: severity
          value: critical
    - name: test-2
      to: "test-2@gmx.de"
      matchers:
        - matchType: "="
          name: severity
          value: warning
