grafanaProvisioning:
  enabled: true
  dashboards:
    enabled: true
    label: grafana_dashboard
    labelValue: "1"
    directory: dashboards
    # Set the folder in which the dashboards will be stored ("General" is not possible)
    grafanaDefaultFolder: Custom
    # Transfer the folder structure from your directory to grafana
    transferFolderStructure: true

# favorite:
#   drink: coffee
#   food: pizza
# pizzaToppings:
#   - mushrooms
#   - cheese
#   - peppers
#   - onions