grafanaProvisioning:
  enabled: true

  dashboards:
    enabled: true
    label: grafana_dashboard
    labelValue: "1"
    directory: dashboards
    subDirectory:
      - Temp

# favorite:
#   drink: coffee
#   food: pizza
# pizzaToppings:
#   - mushrooms
#   - cheese
#   - peppers
#   - onions