apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: a-prometheus-rules-example
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:
    - name: a-prometheus-rules-example
      rules:
        - alert: down
          expr: up == 0
          for: 0m
          labels:
            severity: warning
          annotations:
            summary: prometheus-rules-example
# https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/
# https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/alerting.md
# https://www.youtube.com/watch?v=6xmWr7p5TE0
