kube-prometheus-stack:

  alertmanager:
    enabled: false
    ingress:
      enabled: false

  grafana:
    enabled: true
    defaultDashboardsEnabled: true
    defaultDashboardsTimezone: Europe/Berlin
    adminPassword: admin
    ingress:
      enabled: false
    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
        labelValue: "1"
        searchNamespace: monitoring
        provider:
          allowUiUpdates: false

  prometheusOperator:
    enabled: true

  prometheus:
    enabled: true

  thanosRuler:
    enabled: false


  # Scraping

  kubeApiServer:
    enabled: true
 
  kubelet:
    enabled: true
    
  kubeControllerManager:
    enabled: true

  coreDns:
    enabled: true
  
  kubeDns:
    enabled: false
    
  kubeEtcd:
    enabled: true

  kubeScheduler:
    enabled: true

  kubeProxy:
    enabled: true

  kubeStateMetrics:
    enabled: true

  nodeExporter:
    enabled: true
    operatingSystems:
      linux:
        enabled: true
      darwin:
        enabled: false
