
# alerting:
#   # -- Name of the alert channel as it is defined in the alertforwardings-domain-deployment. The default value is based on `grafanaProvisioningHelpers.domain`.
#   channel: ""
#   # -- Where to read alert JSONs from
#   paths:
#   - "alerts"
# dashboards:
#   # -- Enable provisioned dashboards
#   enabled: true
#   # -- Where to read dashboard JSONs from
#   paths:
#   - "dashboards"



























kube-prometheus-stack:

  alertmanager:
    enabled: false
    ingress:
      enabled: false

  grafana:
    enabled: true
    defaultDashboardsEnabled: true
    defaultDashboardsTimezone: Europe/Berlin
    adminPassword: admin
    ingress:
      enabled: false
    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
        labelValue: "1"
        searchNamespace: monitoring
        provider:
          allowUiUpdates: false

  prometheusOperator:
    enabled: true

  prometheus:
    enabled: true
    # prometheusSpec:
      # additionalScrapeConfigs:
    #   - job_name: 'fritzbox_exporter_fd'
    #     static_configs:
    #     - targets: ['10.10.10.100:10120']

    #   additionalScrapeConfigsSecret: 
    #     enabled: true
    #     name: additional-scrape-configs
    #     key: prometheus-additional.yaml



  thanosRuler:
    enabled: false


  # Scraping

  kubeApiServer:
    enabled: true
 
  kubelet:
    enabled: true
    
  kubeControllerManager:
    enabled: true

  coreDns:
    enabled: true
  
  kubeDns:
    enabled: false
    
  kubeEtcd:
    enabled: true

  kubeScheduler:
    enabled: true

  kubeProxy:
    enabled: true

  kubeStateMetrics:
    enabled: true

  nodeExporter:
    enabled: true
    operatingSystems:
      linux:
        enabled: true
      darwin:
        enabled: false
