# apiVersion: monitoring.coreos.com/v1alpha1
# kind: AlertmanagerConfig
# metadata:
#   name: config-example
#   labels:
#     resource: prometheus
# spec:
#   route:
#     groupBy: ["namespace"]
#     groupWait: 30s
#     groupInterval: 5m
#     repeatInterval: 12h
#     receiver: discord
#     routes:
#       - receiver: discord
#         matchers:
#           - alertname = down
#           - severity =~ "warning|critical"
#   receivers:
#     - name: discord
#       # discordConfigs:
#       #   - apiURL: "https://discordapp.com/api/webhooks/1163728933942997022/aSSYAPj544bpTA5vxv8ebTKWoFLTwKxfmzVGfO47ZATp_quGvXr9JHPLTT9C8mbz6a3t"
