# src: https://blog.container-solutions.com/prometheus-operator-beginners-guide
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-service-monitor
  labels:
    #release: prometheus
    release: monitoring # matchlables: kubectl get prometheuses.monitoring.coreos.com -o yaml -n monitoring
    app: monitoring
spec:
  jobLabel: job
  endpoints:
    - interval: 30s
      port: web
      path: /swagger-stats/metrics
  selector:
    matchLabels:
      app: api
