apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demo
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/mg500/helm-charts'
  destinations:
    - namespace: 'demo'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: 'Namespace'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace: argocd
spec:
  project: demo
  source:
    repoURL: https://github.com/mg500/helm-charts
    targetRevision: main
    path: charts/demo
  destination: 
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true
