apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/mg500/helm-charts'
  destinations:
    - namespace: 'monitoring'
      server: '*'
    - namespace: 'kube-system'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: 'Namespace'
    - group: 'rbac.authorization.k8s.io'
      kind: 'ClusterRole'
    - group: 'rbac.authorization.k8s.io'
      kind: 'ClusterRoleBinding'
    - group: 'admissionregistration.k8s.io'
      kind: 'MutatingWebhookConfiguration'
    - group: 'admissionregistration.k8s.io'
      kind: 'ValidatingWebhookConfiguration'
    - group: 'apiextensions.k8s.io'
      kind: 'CustomResourceDefinition'
  # namespaceResourceWhitelist:
  #   - group: '*'
  #     kind: '*'
  # clusterResourceBlacklist:
  #   - group: '*'
  #     kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: monitoring
  source:
    repoURL: 'https://github.com/mg500/helm-charts'
    targetRevision: main
    path: charts/monitoring
    helm:
      releaseName: monitoring
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      #- Replace=true
      - ServerSideApply=true
      #- ApplyOutOfSyncOnly=true
