apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nana
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/mg500/helm-charts'
  destinations:
    - namespace: 'nana'
      server: '*'
  clusterResourceBlacklist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nana
  namespace: argocd
spec:
  project: nana

  source:
    repoURL: https://github.com/mg500/helm-charts
    targetRevision: HEAD
    path: charts/nana
  destination: 
    server: https://kubernetes.default.svc
    namespace: nana

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
